Cache pyusb backend to avoid segfault issues in libusb destructors
I've been seeing semi-reliable segmentation faults since commit
c1f8b8d049efbc4b216cae47365d16fadf75d1e1:

```
$ DESTRUCTIVE_TEST_YUBIKEY_SERIALS=10616751 DESTRUCTIVE_TEST_DO_NOT_PROMPT=TRUE python setup.py test
[... 234 lines omitted]
test_generate_self_signed_certificate_requires_authentication (test.on_yubikey.test_piv.additional_tests.<locals>.KeyManagement_CCID_5.2.4_10616751) ... ok
test_import_certificate_verifies_key_pairing_eccp384 (test.on_yubikey.test_piv.additional_tests.<locals>.KeyManagement_CCID_5.2.4_10616751) ... Segmentation fault (core dumped)
```

Running with tox and pytest provides a little more detail:

```
$ DESTRUCTIVE_TEST_YUBIKEY_SERIALS=10616751 DESTRUCTIVE_TEST_DO_NOT_PROMPT=TRUE tox -- -v
[... 170 lines omitted]
test/on_yubikey/test_piv.py::TestKeyManagement::test_import_key_requires_authentication[10616751] PASSED                                                                                                                   [ 88%]
test/on_yubikey/test_piv.py::TestKeyManagement::test_read_certificate_does_not_require_authentication[10616751] Fatal Python error: Segmentation fault

Current thread 0x00007f883d646740 (most recent call first):
  File "/home/emlun/dev/yubikey-manager/.tox/py38/lib/python3.8/site-packages/usb/backend/libusb1.py", line 712 in _finalize_object
  File "/home/emlun/dev/yubikey-manager/.tox/py38/lib/python3.8/site-packages/usb/_objfinalizer.py", line 71 in _do_finalize_object
  File "/home/emlun/dev/yubikey-manager/.tox/py38/lib/python3.8/site-packages/usb/_objfinalizer.py", line 104 in _do_finalize_object_ref
  File "/home/emlun/dev/yubikey-manager/.tox/py38/lib/python3.8/weakref.py", line 566 in __call__
  File "/home/emlun/dev/yubikey-manager/.tox/py38/lib/python3.8/site-packages/usb/_objfinalizer.py", line 144 in finalize
  File "/home/emlun/dev/yubikey-manager/.tox/py38/lib/python3.8/site-packages/usb/_objfinalizer.py", line 84 in __del__
  File "/home/emlun/dev/yubikey-manager/test/on_yubikey/test_piv.py", line 58 in reconnect
  File "/home/emlun/dev/yubikey-manager/test/on_yubikey/test_piv.py", line 238 in test_read_certificate_does_not_require_authentication
  File "/home/emlun/dev/yubikey-manager/.tox/py38/lib/python3.8/site-packages/_pytest/python.py", line 167 in pytest_pyfunc_call
  File "/home/emlun/dev/yubikey-manager/.tox/py38/lib/python3.8/site-packages/pluggy/callers.py", line 187 in _multicall
  File "/home/emlun/dev/yubikey-manager/.tox/py38/lib/python3.8/site-packages/pluggy/manager.py", line 84 in <lambda>
  File "/home/emlun/dev/yubikey-manager/.tox/py38/lib/python3.8/site-packages/pluggy/manager.py", line 93 in _hookexec
  File "/home/emlun/dev/yubikey-manager/.tox/py38/lib/python3.8/site-packages/pluggy/hooks.py", line 286 in __call__
  File "/home/emlun/dev/yubikey-manager/.tox/py38/lib/python3.8/site-packages/_pytest/python.py", line 1445 in runtest
  File "/home/emlun/dev/yubikey-manager/.tox/py38/lib/python3.8/site-packages/_pytest/runner.py", line 134 in pytest_runtest_call
  File "/home/emlun/dev/yubikey-manager/.tox/py38/lib/python3.8/site-packages/pluggy/callers.py", line 187 in _multicall
  File "/home/emlun/dev/yubikey-manager/.tox/py38/lib/python3.8/site-packages/pluggy/manager.py", line 84 in <lambda>
  File "/home/emlun/dev/yubikey-manager/.tox/py38/lib/python3.8/site-packages/pluggy/manager.py", line 93 in _hookexec
  File "/home/emlun/dev/yubikey-manager/.tox/py38/lib/python3.8/site-packages/pluggy/hooks.py", line 286 in __call__
  File "/home/emlun/dev/yubikey-manager/.tox/py38/lib/python3.8/site-packages/_pytest/runner.py", line 210 in <lambda>
  File "/home/emlun/dev/yubikey-manager/.tox/py38/lib/python3.8/site-packages/_pytest/runner.py", line 237 in from_call
  File "/home/emlun/dev/yubikey-manager/.tox/py38/lib/python3.8/site-packages/_pytest/runner.py", line 209 in call_runtest_hook
  File "/home/emlun/dev/yubikey-manager/.tox/py38/lib/python3.8/site-packages/_pytest/runner.py", line 185 in call_and_report
  File "/home/emlun/dev/yubikey-manager/.tox/py38/lib/python3.8/site-packages/_pytest/runner.py", line 99 in runtestprotocol
  File "/home/emlun/dev/yubikey-manager/.tox/py38/lib/python3.8/site-packages/_pytest/runner.py", line 84 in pytest_runtest_protocol
  File "/home/emlun/dev/yubikey-manager/.tox/py38/lib/python3.8/site-packages/pluggy/callers.py", line 187 in _multicall
  File "/home/emlun/dev/yubikey-manager/.tox/py38/lib/python3.8/site-packages/pluggy/manager.py", line 84 in <lambda>
  File "/home/emlun/dev/yubikey-manager/.tox/py38/lib/python3.8/site-packages/pluggy/manager.py", line 93 in _hookexec
  File "/home/emlun/dev/yubikey-manager/.tox/py38/lib/python3.8/site-packages/pluggy/hooks.py", line 286 in __call__
  File "/home/emlun/dev/yubikey-manager/.tox/py38/lib/python3.8/site-packages/_pytest/main.py", line 271 in pytest_runtestloop
  File "/home/emlun/dev/yubikey-manager/.tox/py38/lib/python3.8/site-packages/pluggy/callers.py", line 187 in _multicall
  File "/home/emlun/dev/yubikey-manager/.tox/py38/lib/python3.8/site-packages/pluggy/manager.py", line 84 in <lambda>
  File "/home/emlun/dev/yubikey-manager/.tox/py38/lib/python3.8/site-packages/pluggy/manager.py", line 93 in _hookexec
  File "/home/emlun/dev/yubikey-manager/.tox/py38/lib/python3.8/site-packages/pluggy/hooks.py", line 286 in __call__
  File "/home/emlun/dev/yubikey-manager/.tox/py38/lib/python3.8/site-packages/_pytest/main.py", line 247 in _main
  File "/home/emlun/dev/yubikey-manager/.tox/py38/lib/python3.8/site-packages/_pytest/main.py", line 197 in wrap_session
  File "/home/emlun/dev/yubikey-manager/.tox/py38/lib/python3.8/site-packages/_pytest/main.py", line 240 in pytest_cmdline_main
  File "/home/emlun/dev/yubikey-manager/.tox/py38/lib/python3.8/site-packages/pluggy/callers.py", line 187 in _multicall
  File "/home/emlun/dev/yubikey-manager/.tox/py38/lib/python3.8/site-packages/pluggy/manager.py", line 84 in <lambda>
  File "/home/emlun/dev/yubikey-manager/.tox/py38/lib/python3.8/site-packages/pluggy/manager.py", line 93 in _hookexec
  File "/home/emlun/dev/yubikey-manager/.tox/py38/lib/python3.8/site-packages/pluggy/hooks.py", line 286 in __call__
  File "/home/emlun/dev/yubikey-manager/.tox/py38/lib/python3.8/site-packages/_pytest/config/__init__.py", line 92 in main
  File "/home/emlun/dev/yubikey-manager/.tox/py38/bin/pytest", line 11 in <module>
ERROR: InvocationError for command /home/emlun/dev/yubikey-manager/.tox/py38/bin/pytest -v (exited with code -11 (SIGSEGV)) (exited with code -11)
____________________________________________________________________________________________________________ summary _____________________________________________________________________________________________________________
ERROR:   py38: commands failed
```

Apparently something is going wrong in some libusb destructor, but I haven't
been able to track down the exact cause since it only seems to happen when
"enough" load is put on the YubiKey. I was able to reproduce the segmentation
fault while excluding `test/on_yubikey/test_cli_misc.py` and
`test/on_yubikey/test_interfaces.py`, but I was not able to reproduce it if I
excluded any one more test in `test/on_yubikey/`.

Anyway, this change seems to prevent the segmentation fault.