Fix illegal modhex error message
Given the command:

```
ykman otp yubiotp --public-id vvvvvvvvvvvz --generate-private-id --generate-key 2
```

versions before commit bb5ba2d797909a2fbe7174f7958a76eb37762a82 give the error
message:

```
Usage: ykman otp yubiotp [OPTIONS] {1|2}
Try 'ykman otp yubiotp -h' for help.

Error: Invalid public ID, must be modhex.
```

while commit bb5ba2d797909a2fbe7174f7958a76eb37762a82 and later give:

```
Error: substring not found
```

This fixes the regression.